
[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "frame-ancestors 'self' https://storenotify.in https://successrate.netlify.app http://fyersbook.netlify.app http://localhost:8888 http://localhost:4200 https://atmdemoaivenmysql.onrender.com https://rzp.io https://store-stocks.netlify.app https://fyersmarketfeed.onrender.com https://fyersorders.onrender.com https://fyers-positions-socket-git.onrender.com https://onedinaar.com"
     X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "index"
    Cache-Control = "public, max-age=0, no-cache, no-store, must-revalidate"

